name: '自动同步上游仓库'

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '50 1 * * 0,3'

jobs:
  Auto_sync_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: '设置Python环境'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: '安装pip依赖'
        run: |
          pip install -r requirements.txt
      - name: '执行脚本'
        env:
          FORK_TOKEN: ${{ secrets.FORK_TOKEN }}
          GITHUB_ACTOR: ${{ GITHUB_ACTOR }}
        run: python main.py